# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 8) do

  create_table "devices", :force => true do |t|
    t.column "name", :string, :default => "", :null => false
    t.column "partnumber", :string, :default => "", :null => false
    t.column "serialnumber", :string
    t.column "labnumber", :string, :default => "", :null => false
    t.column "device_id", :integer
    t.column "vendor_id", :integer, :default => 0, :null => false
    t.column "location", :string
    t.column "box_location", :string
    t.column "reservation_id", :integer
    t.column "comment", :text
    t.column "serving_property_id", :integer
    t.column "modular", :boolean
  end

  add_index "devices", ["device_id"], :name => "fk_device_device"
  add_index "devices", ["vendor_id"], :name => "fk_device_vendor"
  add_index "devices", ["reservation_id"], :name => "fk_device_reservation"
  add_index "devices", ["serving_property_id"], :name => "fk_device_serving_property"

  create_table "engineers", :force => true do |t|
    t.column "first", :string
    t.column "last", :string
    t.column "middle", :string
    t.column "work_phone", :string
    t.column "cell_phone", :string
    t.column "email", :string
  end

  create_table "interface_types", :force => true do |t|
    t.column "name", :string, :default => "", :null => false
  end

  create_table "interfaces", :force => true do |t|
    t.column "name", :string, :default => "", :null => false
    t.column "interface_type_id", :integer, :default => 0, :null => false
    t.column "device_id", :integer, :default => 0, :null => false
    t.column "interface_id", :integer
  end

  add_index "interfaces", ["interface_type_id"], :name => "fk_interface_interface_type"
  add_index "interfaces", ["device_id"], :name => "fk_interface_device"
  add_index "interfaces", ["interface_id"], :name => "fk_interface_interface"

  create_table "reservations", :force => true do |t|
    t.column "start", :date
    t.column "end", :date
    t.column "comment", :text
    t.column "engineer_id", :integer
  end

  add_index "reservations", ["engineer_id"], :name => "fk_reservation_engineer"

  create_table "serving_properties", :force => true do |t|
    t.column "cpu_count", :integer
    t.column "cpu_type", :string
    t.column "ram", :integer
    t.column "disks_total", :integer
    t.column "disks_layout", :string
    t.column "os", :string
    t.column "admin_login", :string
    t.column "admin_pass", :string
  end

  create_table "users", :force => true do |t|
    t.column "login", :string, :limit => 40
    t.column "password", :string, :limit => 40
  end

  create_table "vendors", :force => true do |t|
    t.column "name", :string, :default => "", :null => false
  end

end
